name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --verbose
